config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'dashboard#index'

  resources :users, except: %i[new create] do
    scope nil, module: :users do
      resource :admins, only: %i[create destroy]

      resources :bookings, only: %i[create show index destroy] do
        scope nil, module: :bookings do
          resource :check_in, only: %i[create destroy]
        end
      end
    end
  end

  resources :airlines
  resources :aircrafts
  resources :airports

  resources :flights
end

app/models/flight.rb
# frozen_string_literal: true

class Flight < ApplicationRecord
  validates :from, :destination, :arrival, :departure, :gate, :number, presence: true

  belongs_to :aircraft

  belongs_to :from, class_name: :Airport
  belongs_to :destination, class_name: :Airport
  belongs_to :gate

  has_one :airline, through: :aircraft

  has_many :bookings

  validate :base_airport_inclusion

  scope :actual, -> do
    where(arel_table[:arrival].gteq(Time.now))
      .or(where(arel_table[:departure].gteq(Time.now)))
      .order(:departure)
  end

  def formatted_number
    "#{airline.shortened} #{number}"
  end

  def arrival?
    from == base_airport
  end

  def departure?
    !arrival?
  end

  private

  def base_airport_inclusion
    return if [from, destination].include?(base_airport)

    errors.add(:base, :base_airport_inclusion)
  end
end

app/controllers/flights_controller.rb
# frozen_string_literal: true

class FlightsController < ApplicationController
  respond_to :html

  skip_before_action :authenticate_user!
  before_action :authorize_admin!, except: %i[index show]
  before_action :authenticate_user!, except: %i[index show]

  helper_method :flights, :flight

  def index
    respond_with flights do |format|
      format.html { render 'index', layout: false } if request.xhr?
    end
  end

  def create
    with_flash_message(flight) { creator.call }

    respond_with flight
  end

  def update
    with_flash_message(flight) { flight.update(flight_params) }

    respond_with flight
  end

  def destroy
    with_flash_message(flight) { flight.destroy }

    respond_with flight
  end

  private

  def flights
    @flights ||= Flight.actual
  end

  def flight
    @flight ||= params[:id] ? Flight.find(params[:id]) : Flight.new
  end

  def creator
    Flights::Creator.new(flight, flight_params)
  end

  def updater
    Flights::Updater.new(flight, flight_params)
  end

  def flight_params
    params
      .require(:flight)
      .permit(
        :from_id,
        :destination_id,
        :departure,
        :arrival,
        :gate_id,
        :aircraft_id,
        :number
      )
  end
end

app/views/flights/_form.html.haml
= simple_form_for flight do |form|
  .form-group
    = form.input :number
  .form-group
    = form.association :aircraft, label_method: :formatted_name
  .form-row
    .form-group.col-md-6
      = form.association :from
    .form-group.col-md-6
      = form.association :destination
  .form-row
    .form-group.col-md-6
      = form.input :departure, as: :datetime_picker
    .form-group.col-md-6
      = form.input :arrival, as: :datetime_picker
  .form-group
    = form.association :gate, collection: base_airport.gates.all, label_method: :formatted_gate_index
  = form.button :submit, class: "btn btn-large btn-primary", "data-disable-with" => "Submitting.."

app/views/flights/edit.html.haml
- model_class = Flight
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/flights/index.html.haml
- model_class = Flight
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped.w-100
  %thead
    %tr
      %th= model_class.human_attribute_name(:flight_number)
      %th= model_class.human_attribute_name(:from)
      %th= model_class.human_attribute_name(:destination)
      %th= model_class.human_attribute_name(:departure)
      %th= model_class.human_attribute_name(:arrival)
      %th= model_class.human_attribute_name(:arrival_gate)
      %th= model_class.human_attribute_name(:departure_gate)
      - if user_signed_in?
        %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - flights.each do |flight|
      %tr
        %td= flight.formatted_number
        %td= flight.from.name
        %td= flight.destination.name
        %td= flight.departure
        %td= flight.arrival
        %td= flight.arrival? ? flight.gate.formatted_gate_index : '-'
        %td= flight.departure? ? flight.gate.formatted_gate_index : '-'
        - if user_signed_in?
          %td
            = link_to t('.book'), user_bookings_path(current_user, booking: { flight_id: flight.id }), method: :post, class: 'btn btn-success btn-xs'
            - if current_user.admin?
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_flight_path(flight), :class => 'btn btn-default btn-xs'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), flight_path(flight), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

- if current_user&.admin? && !request.xhr?
  = link_to t('.new', :default => t("helpers.links.new")), new_flight_path, :class => 'btn btn-primary'

app/views/flights/new.html.haml
- model_class = Flight
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/flights/show.html.haml
- model_class = Flight
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize
%p
  %strong= model_class.human_attribute_name(:from) + ':'
  %br
  = flight.from.name
%p
  %strong= model_class.human_attribute_name(:destination) + ':'
  %br
  = flight.destination.name
%p
  %strong= model_class.human_attribute_name(:departure) + ':'
  %br
  = flight.departure
%p
  %strong= model_class.human_attribute_name(:arrival) + ':'
  %br
  = flight.arrival


= link_to t('.back', :default => t("helpers.links.back")), flights_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_flight_path(flight), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), flight_path(flight), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'