config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'dashboard#index'

  resources :users, except: %i[new create] do
    scope nil, module: :users do
      resource :admins, only: %i[create destroy]

      resources :bookings, only: %i[create show index destroy] do
        scope nil, module: :bookings do
          resource :check_in, only: %i[create destroy]
        end
      end
    end
  end

  resources :airlines
  resources :aircrafts
  resources :airports

  resources :flights
end

app/models/airport.rb
# frozen_string_literal: true

class Airport < ApplicationRecord
  validates :name, :iata, :icao, :country, presence: true

  has_many :gates
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  respond_to :html

  before_action :authorize_admin!

  helper_method :airports, :airport

  def index
    respond_with airports
  end

  def create
    with_flash_message(airport) do
      airport.assign_attributes(airport_params)

      airport.save
    end

    respond_with airport
  end

  def update
    with_flash_message(airport) { airport.update(airport_params) }

    respond_with airport
  end

  def destroy
    with_flash_message(airport) { airport.destroy }

    respond_with airport
  end

  private

  def airports
    @airports ||= Airport.all
  end

  def airport
    @airport ||= params.key?(:id) ? Airport.find(params[:id]) : Airport.new
  end

  def airport_params
    params.require(:airport).permit(:manufacturer, :model, :capacity, :airline_id)
  end
end

app/views/airports/_form.html.haml
= simple_form_for airport do |form|
  .form-group
    = form.input :name
  .form-group
    = form.input :icao
  .form-group
    = form.input :iata
  .form-group
    = form.input :country
  = form.button :submit, class: "btn btn-large btn-primary", "data-disable-with" => "Submitting.."

app/views/airports/edit.html.haml
- model_class = Airport
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/airports/index.html.haml
- model_class = Airport
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped.w-100
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:icao)
      %th= model_class.human_attribute_name(:iata)
      %th= model_class.human_attribute_name(:country)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - airports.each do |airport|
      %tr
        %td= airport.name
        %td= airport.icao
        %td= airport.iata
        %td= airport.country
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_airport_path(airport), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), airport_path(airport), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_airport_path, :class => 'btn btn-primary'

app/views/airports/new.html.haml
- model_class = Airport
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/airports/show.html.haml
- model_class = Airport
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = airport.name
%p
  %strong= model_class.human_attribute_name(:icao) + ':'
  %br
  = airport.icao
%p
  %strong= model_class.human_attribute_name(:iata) + ':'
  %br
  = airport.iata
%p
  %strong= model_class.human_attribute_name(:country) + ':'
  %br
  = airport.country

= link_to t('.back', :default => t("helpers.links.back")), airports_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_airport_path(airport), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), airport_path(airport), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'