config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'dashboard#index'

  resources :users, except: %i[new create] do
    scope nil, module: :users do
      resource :admins, only: %i[create destroy]

      resources :bookings, only: %i[create show index destroy] do
        scope nil, module: :bookings do
          resource :check_in, only: %i[create destroy]
        end
      end
    end
  end

  resources :airlines
  resources :aircrafts
  resources :airports

  resources :flights
end

app/models/airline.rb
# frozen_string_literal: true

class Airline < ApplicationRecord
  validates :name, :shortened, presence: true

  has_many :aircrafts, dependent: :destroy
  has_many :flights, through: :aircrafts
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  respond_to :html

  before_action :authorize_admin!

  helper_method :airlines, :airline

  def index
    respond_with airlines
  end

  def create
    with_flash_message(airline) do
      airline.assign_attributes(airline_params)

      airline.save
    end

    respond_with airline
  end

  def update
    with_flash_message(airline) { airline.update(airline_params) }

    respond_with airline
  end

  def destroy
    with_flash_message(airline) { airline.destroy }

    respond_with airline
  end

  private

  def airlines
    @airlines ||= Airline.all
  end

  def airline
    @airline ||= params.key?(:id) ? Airline.find(params[:id]) : Airline.new
  end

  def airline_params
    params.require(:airline).permit(:name, :shortened)
  end
end

app/views/airlines/_form.html.haml
= simple_form_for airline do |form|
  .form-group
    = form.input :name
  .form-group
    = form.input :shortened
  = form.button :submit, class: "btn btn-large btn-primary", "data-disable-with" => "Submitting.."

app/views/airlines/edit.html.haml
- model_class = Airline
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/airlines/index.html.haml
- model_class = Airline
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped.w-100
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:shortened)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - airlines.each do |airline|
      %tr
        %td= airline.name
        %td= airline.shortened
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_airline_path(airline), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), airline_path(airline), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_airline_path, :class => 'btn btn-primary'

app/views/airlines/new.html.haml
- model_class = Airline
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/airlines/show.html.haml
- model_class = Airline
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = airline.name
%p
  %strong= model_class.human_attribute_name(:shortened) + ':'
  %br
  = airline.shortened

= link_to t('.back', :default => t("helpers.links.back")), airlines_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_airline_path(airline), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), airline_path(airline), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'