config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'dashboard#index'

  resources :users, except: %i[new create] do
    scope nil, module: :users do
      resource :admins, only: %i[create destroy]

      resources :bookings, only: %i[create show index destroy] do
        scope nil, module: :bookings do
          resource :check_in, only: %i[create destroy]
        end
      end
    end
  end

  resources :airlines
  resources :aircrafts
  resources :airports

  resources :flights
end

app/views/layouts/_footer.html.haml
%footer.footer
  %p NOT FOR REAL USE. LPNU KN-22z Oleksii Hashparych 2019

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href=root_path) Airport
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li= link_to t(:title, scope: :flights), flights_path
        - if current_user&.admin?
          %li= link_to t(:title, scope: :users), users_path
          %li= link_to t(:title, scope: :aircrafts), aircrafts_path
          %li= link_to t(:title, scope: :airlines), airlines_path
          %li= link_to t(:title, scope: :airports), airports_path
      = render 'layouts/user_items'

app/views/layouts/_user_items.html.haml
%ul.nav.navbar-nav.pull-right
  - if user_signed_in?
    %li= link_to t(:title, scope: %i[users bookings]), user_bookings_path(current_user)
    %li= link_to t(:edit_profile, scope: :users), edit_user_registration_path
    %li= link_to t(:logout, scope: :users), destroy_user_session_path, method: :delete
  - else
    %li= link_to t(:sign_up, scope: :users), new_user_registration_path
    %li= link_to t(:login, scope: :users), new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Airport"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  %body
    = render 'layouts/header'

    .container
      .row
        = bootstrap_flash
        = yield
      = render 'layouts/footer'